#!/usr/bin/env python3
"""
Reddit Video Scheduler
Picks an unused topic from topics.json, runs make_reddit_video.py, marks it used.
Cycles back through all topics once all have been used.

Local usage:  python3 scheduler.py
Cloud usage:  runs automatically via GitHub Actions (env var CLOUD_MODE=true)
"""

import os
import json
import random
import subprocess
import sys
import logging
from pathlib import Path
from datetime import datetime, timezone

# ── Cloud mode detection ────────────────────────────────────────────────────
CLOUD_MODE = os.getenv("CLOUD_MODE", "false").lower() == "true"

# ── Paths ────────────────────────────────────────────────────────────────────
if CLOUD_MODE:
    # GitHub Actions: everything is relative to the repo root (workspace)
    BASE_DIR = Path(__file__).parent
else:
    BASE_DIR = Path("/Users/vincent/Desktop/Reddit AI Videos")

TOPICS_FILE  = BASE_DIR / "topics.json"
SCRIPT       = BASE_DIR / "make_reddit_video.py"
LOG_FILE     = BASE_DIR / "scheduler.log"
OUTPUT_DIR   = BASE_DIR / "output"
PYTHON       = sys.executable

OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

# ── Logging ──────────────────────────────────────────────────────────────────
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s  %(levelname)s  %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
    handlers=[
        logging.FileHandler(LOG_FILE, encoding="utf-8"),
        logging.StreamHandler(sys.stdout),
    ],
)
log = logging.getLogger(__name__)


def load_topics():
    with open(TOPICS_FILE, "r", encoding="utf-8") as f:
        return json.load(f)


def save_topics(data):
    with open(TOPICS_FILE, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)


def pick_topic(data: dict) -> dict | None:
    unused = [t for t in data["topics"] if not t["used"]]
    return random.choice(unused) if unused else None


def reset_topics(data: dict):
    for t in data["topics"]:
        t["used"] = False
    log.info("All topics used — resetting cycle.")


def mark_used(data: dict, topic_text: str):
    for t in data["topics"]:
        if t["topic"] == topic_text:
            t["used"] = True
            break


def run_video(topic: str, audience: str) -> tuple[bool, str]:
    """
    Run make_reddit_video.py.
    Returns (success, output_text).
    In cloud mode, captures stdout so we can parse the video URL and caption.
    """
    log.info(f"Topic:    {topic!r}")
    log.info(f"Audience: {audience}")

    result = subprocess.run(
        [PYTHON, str(SCRIPT), "--topic", topic, "--audience", audience],
        capture_output=CLOUD_MODE,
        text=True,
    )

    output = (result.stdout or "") + (result.stderr or "")

    if result.returncode != 0:
        log.error(f"Script exited {result.returncode}")
        if CLOUD_MODE:
            log.error(output)
        return False, output

    if CLOUD_MODE:
        log.info(output)

    log.info("Video generation complete.")
    return True, output


def save_cloud_result(topic: str, audience: str, output: str):
    """
    Parse the script output for the video URL and caption,
    then write a dated markdown file to output/ so it's committed to the repo.
    """
    now_utc  = datetime.now(timezone.utc).strftime("%Y-%m-%d_%H-%M-UTC")
    md_path  = OUTPUT_DIR / f"{now_utc}.md"

    # Try to extract the Shotstack video URL and caption from stdout
    video_url = ""
    caption   = ""
    for line in output.splitlines():
        if "shotstack" in line.lower() and "http" in line:
            video_url = line.strip().split()[-1]
        if "caption:" in line.lower():
            caption = line.split(":", 1)[-1].strip()

    md = f"""# Reddit Video — {now_utc}

**Topic:** {topic}
**Audience:** {audience}

## Video Download Link
{video_url if video_url else "*(check scheduler.log for the Shotstack render URL)*"}

## Caption & Hashtags
```
{caption if caption else "*(check scheduler.log)*"}
```

---
*Auto-generated by Reddit Video Bot*
"""
    md_path.write_text(md, encoding="utf-8")
    log.info(f"Results saved → output/{md_path.name}")


def main():
    log.info("=" * 60)
    log.info(f"Scheduler triggered — {'CLOUD' if CLOUD_MODE else 'LOCAL'} mode")
    log.info(f"Time: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}")

    data = load_topics()

    entry = pick_topic(data)
    if entry is None:
        reset_topics(data)
        save_topics(data)
        entry = pick_topic(data)

    topic    = entry["topic"]
    audience = entry["audience"]

    mark_used(data, topic)
    save_topics(data)

    remaining = sum(1 for t in data["topics"] if not t["used"])
    log.info(f"Topics remaining after this run: {remaining}")

    success, output = run_video(topic, audience)

    if CLOUD_MODE:
        save_cloud_result(topic, audience, output)

    if not success:
        log.warning("Video failed — topic still marked used to avoid infinite retry.")
        sys.exit(1)

    log.info("=" * 60)


if __name__ == "__main__":
    main()
